Particular/NServiceBus.Newtonsoft.Json

- packaging/nuget/NServiceBus.Newtonsoft.Json.nuspec
- src/NServiceBus.Newtonsoft.Json/NServiceBus.Newtonsoft.Json.csproj
- src/NServiceBus.Newtonsoft.Json/NewtonsoftConfigurationExtensions.cs
- src/NServiceBus.Newtonsoft.Json/packages.config
- src/Sample/Sample.csproj
- src/Sample/packages.config
- src/Tests/APIApprovals.Approve.approved.txt
- src/Tests/APIApprovals.cs
- src/Tests/Tests.csproj
- src/Tests/packages.config
relates to https://github.com/Particular/NServiceBus/pull/3781
updates to nsb beta4
> Rename extentions to extensions

- GitVersion.yml
- src/NServiceBus.Newtonsoft.Json/NServiceBus.Newtonsoft.Json.csproj
- src/NServiceBus.Newtonsoft.Json/packages.config
Connects to https://github.com/Particular/V6Launch/issues/3
> Upgrade GitVersion 3.6.3

- src/NServiceBus.Newtonsoft.Json/JsonMessageSerializer.cs
- src/Tests/JsonMessageSerializerTest.cs
Same changes as proposed here: https://github.com/Particular/NServiceBus/pull/4367
please have a look @SimonCropp
> Preserve DateTimeOffset timezones

- src/NServiceBus.Newtonsoft.Json/JsonMessageSerializer.cs
- src/Tests/ArrayTests.Should_not_throw_for_single_dollar.approved.txt
- src/Tests/ArrayTests.Should_not_throw_for_single_passed_type.approved.txt
- src/Tests/ArrayTests.Should_throw_for_multiple_dollar.approved.txt
- src/Tests/ArrayTests.Should_throw_for_multiple_passed_type.approved.txt
- src/Tests/ArrayTests.cs
- src/Tests/Tests.csproj
v3 and v4 still wrap single messages in an array
> better array handling

- .gitattributes
- .gitignore
- src/Directory.Build.props
- src/NServiceBus.Newtonsoft.Json.sln
- src/NServiceBus.Newtonsoft.Json.sln.DotSettings
- src/NServiceBus.Newtonsoft.Json/NServiceBus.Newtonsoft.Json.csproj
- src/Sample/Sample.csproj
- src/Tests/Tests.csproj
Here are a few more misc things to clean up post-conversion, and to make the core-maintained projects more consistent.
There's nothing here that would require a new beta package to be pushed.
> Project cleanup

- src/NServiceBus.Newtonsoft.Json/NServiceBus.Newtonsoft.Json.csproj
- src/Tests/Tests.csproj
This is based against develop in preparation for a 2.1.0-beta1 release.
> Update Newtonsoft.Json to 11.0.1

- src/NServiceBus.Newtonsoft.Json/NServiceBus.Newtonsoft.Json.csproj
- src/Tests/Tests.csproj
> Update Newtonsoft.Json to 12.0.1

- GitVersion.yml
- src/NServiceBus.Newtonsoft.Json/NServiceBus.Newtonsoft.Json.csproj
> Update Particular.Packaging in master

- GitVersion.yml
- src/NServiceBus.Newtonsoft.Json/NServiceBus.Newtonsoft.Json.csproj
> Update Particular.Packaging in release-2.2

- src/Sample/Sample.csproj
- src/Tests/Tests.csproj
For your review @mauroservienti
> Update test projects to netcoreapp3.1 in release-2.2

- src/Tests/Tests.csproj
For your review @mauroservienti
> Update test projects to NServiceBus 7.2.3 in release-2.2

- src/NServiceBus.Newtonsoft.Json/NServiceBus.Newtonsoft.Json.csproj
Target framework update to netcoreapp2.1 as part of https://github.com/Particular/Exploration/issues/482
> target framework upgrade

- src/NServiceBus.Newtonsoft.Json/NServiceBus.Newtonsoft.Json.csproj
- src/Tests/Tests.csproj
Didn't we intent to add tokens to the serializer API?
> Update to core 917

- src/NServiceBus.Newtonsoft.Json/NServiceBus.Newtonsoft.Json.csproj
Thanks to @SimonCropp for pointing out the missing description.
> add package description

- .github/workflows/ci.yml
- .github/workflows/release.yml
Workflow updates based on https://github.com/Particular/KeepTheLightsOn/issues/1103
> Workflow updates - main

- .github/workflows/ci.yml
- .github/workflows/release.yml
Workflow updates based on https://github.com/Particular/KeepTheLightsOn/issues/1103
> Workflow updates - 2.4

- .github/workflows/ci.yml
- .github/workflows/release.yml
Workflow updates based on https://github.com/Particular/KeepTheLightsOn/issues/1103
> Workflow updates - 2.3

- .component-package.yml
- .component_package.yml
This PR adds  a metadata file to the repo that specifies the component packages that are generated as part of the assets in release work flow
> add metadata component_package.yml

- .component-package.yml
Reverts Particular/NServiceBus.Newtonsoft.Json#502
Reverting this PR as component packages that are generated as part of the assets in release work flow will be read from centralized file
> Revert "add metadata component_package.yml"

- src/Tests/DataBus/When_sending_databus_properties.cs
- src/Tests/DataBus/When_sending_unobtrusive_databus_properties.cs
- src/Tests/JsonMessageSerializerTest.cs
- src/Tests/Private_with_two_unrelated_interface_without_wrapping.cs
- src/Tests/Tests.csproj
- src/Tests/TypeNameHandlingTests.cs
- src/Tests/When_deserializing_a_message.cs
- src/Tests/When_serializing_a_message.cs
- src/Tests/With_base_but_without_concrete.cs
- src/Tests/With_concrete_implementation_and_interface.cs
- src/Tests/With_interface_without_wrapping.cs
- src/Tests/Without_concrete_implementation_and_interface.cs
- src/Tests/Without_typeInfo.cs
- src/Tests/Without_wrapping.cs
This PR contains all changes related to assertion model according to the [constraint assertion model](https://docs.nunit.org/articles/nunit/writing-tests/assertions/assertion-models/constraint.html).
Using a script, we apply all [assertion rules](https://docs.nunit.org/articles/nunit-analyzers/NUnit-Analyzers.html#assertion-rules-nunit2001---) provided by the NUnit.Analyzers package. In addition, some manual interventions are done when applicable.
> Migrate NUnit assertions to the constraint model in preparation of the NUnit 4 upgrade

- src/Tests/DataBus/When_sending_databus_properties.cs
- src/Tests/DataBus/When_sending_unobtrusive_databus_properties.cs
- src/Tests/DataBus/When_serializing_a_message_with_databus_property.cs
- src/Tests/Tests.csproj
This PR contains all changes related to NUnit4 upgrade including all required dependencies.
The following packages are checked for necessary upgrades but might not necessarily be in the change set if they are not present:
- NServiceBus
- NServiceBus.AcceptanceTesting
- NServiceBus.AcceptanceTests.Sources
- NServiceBus.PersistenceTests.Sources
- NServiceBus.TransportTests.Sources
- NUnit
In addition, some manual interventions are done when applicable.
> Upgrading to NUnit4 including all required dependencies

- src/Tests/JsonMessageSerializerTest.cs
Follow through for https://github.com/Particular/NServiceBus.Newtonsoft.Json/pull/516
> Address Assert.Multiple weirdness
